# Generated by Django 5.2.8 on 2025-11-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_below_min',
            field=models.BooleanField(default=False),
        ),
    ]
