# Generated by Django 5.2.8 on 2025-12-01 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stock_is_below_min'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='user',
            new_name='id_user',
        ),
    ]
