# Generated by Django 5.2.8 on 2025-12-03 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_user_log_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api.product', unique=True),
        ),
    ]
